---
- name: Install RKE2 Agent (Worker Nodes)
  hosts: workers
  become: yes

  vars:
    master_ip: "192.168.56.101"
    token: "{{ lookup('file', '/var/lib/jenkins/workspace/rke2-ansible-pipeline/cluster-token.txt') }}"

  tasks:

    - name: Download RKE2 installer
      get_url:
        url: https://get.rke2.io
        dest: /tmp/rke2-install.sh
        mode: '0755'

    - name: Create RKE2 config directory
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: Create worker config.yaml
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          server: "https://{{ master_ip }}:9345"
          token: "{{ token }}"
          node-ip: "{{ ansible_default_ipv4.address }}"
          resolv-conf: "/etc/resolv.conf"
        mode: '0644'

    - name: Install RKE2 agent
      shell: INSTALL_RKE2_VERSION=v1.33.6+rke2r1 INSTALL_RKE2_TYPE=agent sh /tmp/rke2-install.sh

    - name: Enable and start rke2-agent
      systemd:
        name: rke2-agent
        enabled: yes
        state: started
